### ISSUE TITLE
RSS seems not to work

### ISSUE THREAD

**Issue by kweinert** [RMHogervorst/blog#20]
when I add 

https://blog.rmhogervorst.nl/index.xml

to my feedly account, I only see posts from 2019.

**Comment by RMHogervorst** [comment]
Hi @kweinert, 
I think this has to do with the way hugo sets up the feeds. 
I think your selection only returns posts without any category. 
I created a small description here: https://blog.rmhogervorst.nl/subscribing .
If you add 
https://blog.rmhogervorst.nl/categories/r/index.xml  to your feed it will show all R posts. 

You can even use a tag specific RSS feed if you'd like:
This will give you all the posts with the tag 'intermediate' 
https://blog.rmhogervorst.nl//tags/intermediate/index.xml
